name: custom_scroll_view
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0-334.2.beta

dependencies:
  flutter:
    sdk: flutter
  flutter_carousel_widget: ^3.1.0
  carousel_slider: ^5.0.0
  flutter_svg: ^2.0.16
  shimmer: ^3.0.0
  smooth_page_indicator: ^1.2.0+3
  google_maps_flutter: ^2.10.0
  path_provider: ^2.1.5
  geocoding: ^3.0.0
  sqflite: ^2.4.1
  flutter_bloc: ^9.0.0
  flutter_bounceable: ^1.2.0
  cached_network_image: ^3.4.1
  shared_preferences: ^2.5.2
  flutter_swipe_button: ^2.1.3
  # Search
  animation_search_bar: ^0.0.10

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
